"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/Header.css";
import { create } from 'zustand'

import React, { Component, Suspense, lazy, useState, useEffect } from 'react'
import { isMobile } from 'react-device-detect';
import Header from './_components/Header';
// import MainPage from './Pages/MainPage';
// import Checkout from './Pages/Checkout';
import PriceFooter from './_components/PriceFooter';
import { useStore } from './_stores/main';

// const User = lazy(() => import('./Pages/User'));
// const Login = lazy(() => import('./Pages/Login'));
// const ProductPage = lazy(() => import('./Pages/ProductPage'));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const is_checkout_list_empty = useStore((state: any) => state.is_checkout_list_empty);

  const pathname = window.location.pathname;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header/>
        {children}
        {(is_checkout_list_empty === false && pathname !== '/login') && (is_checkout_list_empty === false && pathname !== '/checkout') &&
          <React.Fragment>
            {(isMobile && is_checkout_list_empty === false && pathname === '/') &&
              <PriceFooter/>
            }
            {!isMobile &&
              <PriceFooter/>
            }
          </React.Fragment>
        }
      </body>
    </html>
  );
}
